// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TestType.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__TESTMODULE_TESTTYPE_HPP
#define FAST_DDS_GENERATED__TESTMODULE_TESTTYPE_HPP

#include <array>
#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TESTTYPE_SOURCE)
#define TESTTYPE_DllAPI __declspec( dllexport )
#else
#define TESTTYPE_DllAPI __declspec( dllimport )
#endif // TESTTYPE_SOURCE
#else
#define TESTTYPE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TESTTYPE_DllAPI
#endif // _WIN32

namespace TestModule {

/*!
 * @brief This class represents the structure TestType defined by the user in the IDL file.
 * @ingroup TestType
 */
class TestType
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TestType()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TestType()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TestType that will be copied.
     */
    eProsima_user_DllExport TestType(
            const TestType& x)
    {
                    m_seq = x.m_seq;

                    m_message = x.m_message;

                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TestType that will be copied.
     */
    eProsima_user_DllExport TestType(
            TestType&& x) noexcept
    {
        m_seq = x.m_seq;
        m_message = std::move(x.m_message);
        m_data = std::move(x.m_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TestType that will be copied.
     */
    eProsima_user_DllExport TestType& operator =(
            const TestType& x)
    {

                    m_seq = x.m_seq;

                    m_message = x.m_message;

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TestType that will be copied.
     */
    eProsima_user_DllExport TestType& operator =(
            TestType&& x) noexcept
    {

        m_seq = x.m_seq;
        m_message = std::move(x.m_message);
        m_data = std::move(x.m_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x TestType object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TestType& x) const
    {
        return (m_seq == x.m_seq &&
           m_message == x.m_message &&
           m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x TestType object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TestType& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member seq
     * @param _seq New value for member seq
     */
    eProsima_user_DllExport void seq(
            uint64_t _seq)
    {
        m_seq = _seq;
    }

    /*!
     * @brief This function returns the value of member seq
     * @return Value of member seq
     */
    eProsima_user_DllExport uint64_t seq() const
    {
        return m_seq;
    }

    /*!
     * @brief This function returns a reference to member seq
     * @return Reference to member seq
     */
    eProsima_user_DllExport uint64_t& seq()
    {
        return m_seq;
    }


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const eprosima::fastcdr::fixed_string<128>& _message)
    {
        m_message = _message;
    }

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            eprosima::fastcdr::fixed_string<128>&& _message)
    {
        m_message = std::move(_message);
    }

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<128>& message() const
    {
        return m_message;
    }

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<128>& message()
    {
        return m_message;
    }


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::array<uint8_t, 1024>& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::array<uint8_t, 1024>&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::array<uint8_t, 1024>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::array<uint8_t, 1024>& data()
    {
        return m_data;
    }



private:

    uint64_t m_seq{0};
    eprosima::fastcdr::fixed_string<128> m_message;
    std::array<uint8_t, 1024> m_data{0};

};

} // namespace TestModule

#endif // _FAST_DDS_GENERATED_TESTMODULE_TESTTYPE_HPP_


